/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LumuksoSocialRecovery } from "./LumuksoSocialRecovery";
export * as factories from "./factories";
export { LumuksoSocialRecovery__factory } from "./factories/LumuksoSocialRecovery__factory";
