/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { UniversalProfile } from "./UniversalProfile";
export * as factories from "./factories";
export { UniversalProfile__factory } from "./factories/UniversalProfile__factory";
