/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface LumuksoUtilsInterface extends utils.Interface {
  functions: {
    "checkSocialRecoveryPermissions(address,address)": FunctionFragment;
    "getSocialRecoveryPermissionKeyValues(address,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "checkSocialRecoveryPermissions"
      | "getSocialRecoveryPermissionKeyValues"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkSocialRecoveryPermissions",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getSocialRecoveryPermissionKeyValues",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkSocialRecoveryPermissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSocialRecoveryPermissionKeyValues",
    data: BytesLike
  ): Result;

  events: {};
}

export interface LumuksoUtils extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LumuksoUtilsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    checkSocialRecoveryPermissions(
      profile: PromiseOrValue<string>,
      socialRecovery: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getSocialRecoveryPermissionKeyValues(
      profile: PromiseOrValue<string>,
      socialRecovery: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string[], string[]]>;
  };

  checkSocialRecoveryPermissions(
    profile: PromiseOrValue<string>,
    socialRecovery: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getSocialRecoveryPermissionKeyValues(
    profile: PromiseOrValue<string>,
    socialRecovery: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<[string[], string[]]>;

  callStatic: {
    checkSocialRecoveryPermissions(
      profile: PromiseOrValue<string>,
      socialRecovery: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getSocialRecoveryPermissionKeyValues(
      profile: PromiseOrValue<string>,
      socialRecovery: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string[], string[]]>;
  };

  filters: {};

  estimateGas: {
    checkSocialRecoveryPermissions(
      profile: PromiseOrValue<string>,
      socialRecovery: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSocialRecoveryPermissionKeyValues(
      profile: PromiseOrValue<string>,
      socialRecovery: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    checkSocialRecoveryPermissions(
      profile: PromiseOrValue<string>,
      socialRecovery: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSocialRecoveryPermissionKeyValues(
      profile: PromiseOrValue<string>,
      socialRecovery: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
